services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: callen
      POSTGRES_USER: callen
      POSTGRES_PASSWORD: callenpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

