# Generated by Django 5.2.6 on 2025-10-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='pages/about/'),
        ),
        migrations.AddField(
            model_name='page',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='pages/about/'),
        ),
    ]
