# Generated by Django 5.2.6 on 2025-10-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_page_image_one_page_image_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Welcome to Callen Kennels & Ruff House Dog Supplies LLC!', max_length=200)),
                ('left_title', models.CharField(default='Callen Kennels', max_length=120)),
                ('left_blurb', models.TextField(blank=True)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('left_link', models.CharField(default='/page/about/', help_text='Internal path or full URL (e.g. /page/about/ or https://...)', max_length=200)),
                ('right_title', models.CharField(default='Ruff House Dog Supplies LLC', max_length=160)),
                ('right_blurb', models.TextField(blank=True)),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('right_link', models.CharField(default='/ruff-house/supplies/', help_text='Internal path or full URL', max_length=200)),
                ('contact_heading', models.CharField(default='Contact Information', max_length=120)),
                ('contact_name', models.CharField(default='Sue Callen', max_length=120)),
                ('contact_phone', models.CharField(blank=True, default='518-XXX-XXXX', max_length=60)),
                ('contact_email', models.EmailField(blank=True, default='tsuc4954@gmail.com', max_length=254)),
                ('contact_address', models.CharField(blank=True, default='140 Littner Rd, Rensselaerville, NY', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage',
                'verbose_name_plural': 'Homepage',
            },
        ),
    ]
