# Generated by Django 5.2.6 on 2025-10-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='left_button_label',
            field=models.CharField(blank=True, default='Learn More', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='right_button_label',
            field=models.CharField(blank=True, default='View Supplies', max_length=40),
        ),
    ]
