# Generated by Django 5.2.6 on 2025-10-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_homepage_left_button_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Callen Kennels', max_length=120)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('intro_paragraph', models.TextField(blank=True)),
                ('body_paragraph', models.TextField(blank=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
    ]
