# Generated by Django 5.2.6 on 2025-11-01 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_aboutpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBreedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About the Breed', max_length=120)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('intro_paragraph', models.TextField(blank=True, help_text='Top paragraph describing the Miniature American Shepherd.')),
                ('height', models.CharField(blank=True, default='', max_length=120)),
                ('weight', models.CharField(blank=True, default='', max_length=120)),
                ('colors', models.CharField(blank=True, default='', max_length=200)),
                ('eyes', models.CharField(blank=True, default='', max_length=200)),
                ('coat', models.CharField(blank=True, default='', max_length=200)),
                ('temperament', models.CharField(blank=True, default='', max_length=250)),
                ('breed_tendencies', models.CharField(blank=True, default='', max_length=250)),
                ('exercise_needed', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About the Breed Page',
                'verbose_name_plural': 'About the Breed Page',
            },
        ),
    ]
