# Generated by Django 5.2.6 on 2025-11-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_aboutbreedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='breed_tendencies',
            field=models.CharField(blank=True, default='Herding Behavior, Guardian Instinct', max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='coat',
            field=models.CharField(blank=True, default='Medium Double Coat', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='colors',
            field=models.CharField(blank=True, default='Black Tri, Red Tri, Blue Merle, Red Merle', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='exercise_needed',
            field=models.CharField(blank=True, default='Moderate', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='eyes',
            field=models.CharField(blank=True, default='Blue, Brown, Hazel, Amber', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='height',
            field=models.CharField(blank=True, default='14-18 inches', max_length=120),
        ),
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='temperament',
            field=models.CharField(blank=True, default='Intelligent, Energetic, Loyal, Trainable', max_length=250),
        ),
        migrations.AlterField(
            model_name='aboutbreedpage',
            name='weight',
            field=models.CharField(blank=True, default='20-40 lbs', max_length=120),
        ),
    ]
