# Generated by Django 4.2.13 on 2025-11-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_alter_aboutbreedpage_breed_tendencies_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="puppy", name="contract_pdf",),
        migrations.RemoveField(model_name="puppy", name="health_notes",),
        migrations.RemoveField(model_name="puppy", name="main_photo",),
        migrations.AddField(
            model_name="puppy",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="puppy",
            name="photo_1",
            field=models.ImageField(blank=True, null=True, upload_to="puppies/"),
        ),
        migrations.AddField(
            model_name="puppy",
            name="photo_2",
            field=models.ImageField(blank=True, null=True, upload_to="puppies/"),
        ),
        migrations.AddField(
            model_name="puppy",
            name="photo_3",
            field=models.ImageField(blank=True, null=True, upload_to="puppies/"),
        ),
        migrations.AddField(
            model_name="puppy",
            name="photo_4",
            field=models.ImageField(blank=True, null=True, upload_to="puppies/"),
        ),
    ]
