# Generated by Django 4.2.13 on 2025-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0008_remove_puppy_contract_pdf_remove_puppy_health_notes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PuppiesPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Puppies Available Now! • Callen Kennels",
                        help_text="Browser tab title.",
                        max_length=150,
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="Puppies Available Now!",
                        help_text="Big heading shown above the puppies list.",
                        max_length=150,
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image shown at the top of the page (e.g. Callen logo).",
                        null=True,
                        upload_to="puppies/header/",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Puppies Available Page",
                "verbose_name_plural": "Puppies Available Page",
            },
        ),
    ]
