# Generated by Django 4.2.13 on 2025-12-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_suppliespage"),
    ]

    operations = [
        migrations.CreateModel(
            name="GirlsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="My Girls • Callen Kennels",
                        help_text="Browser tab title.",
                        max_length=150,
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        default="My Girls",
                        help_text="Big heading shown at the top of the My Girls page.",
                        max_length=150,
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        help_text="Image shown at top-left under the nav.",
                        null=True,
                        upload_to="dogs/header/",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "My Girls Page",
                "verbose_name_plural": "My Girls Page",
            },
        ),
    ]
