# Generated by Django 4.2.13 on 2026-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_pastlitterspage"),
    ]

    operations = [
        migrations.CreateModel(
            name="PastPuppy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "litter_name",
                    models.CharField(
                        blank=True,
                        help_text='Example: "Salem x Dunkin" or "Litter A"',
                        max_length=120,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "puppy_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="past_puppies/puppy/"
                    ),
                ),
                (
                    "adult_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="past_puppies/adult/"
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Past Puppy",
                "verbose_name_plural": "Past Puppies",
                "ordering": ["-birth_date", "name"],
            },
        ),
    ]
