# Generated by Django 4.2.13 on 2026-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_pastpuppy"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="left_small_logo",
            field=models.ImageField(blank=True, null=True, upload_to="home/"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="right_small_logo",
            field=models.ImageField(blank=True, null=True, upload_to="home/"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subheading",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
