# Generated by Django 4.2.13 on 2026-02-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_homepage_left_small_logo_homepage_right_small_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliespage",
            name="box_1_body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="suppliespage",
            name="box_1_title",
            field=models.CharField(
                blank=True, default="How to Purchase", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="suppliespage",
            name="box_2_title",
            field=models.CharField(
                blank=True, default="Upcoming Events", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="suppliespage",
            name="show_box_1",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="suppliespage",
            name="show_box_2",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="UpcomingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Event", max_length=120)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "supplies_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upcoming_events",
                        to="website.suppliespage",
                    ),
                ),
            ],
            options={"ordering": ["sort_order", "start"],},
        ),
    ]
