# Generated by Django 4.2.13 on 2026-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_suppliespage_box_1_body_suppliespage_box_1_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upcomingevent",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upcomingevent",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
