# Generated by Django 4.2.13 on 2026-02-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_upcomingevent_end_time_upcomingevent_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upcomingevent",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="upcomingevent", name="start", field=models.DateField(),
        ),
    ]
