# Generated by Django 4.2.13 on 2026-02-18 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_alter_upcomingevent_end_alter_upcomingevent_start"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="upcomingevent",
            options={"ordering": ["sort_order", "start_date", "start_time"]},
        ),
        migrations.RenameField(
            model_name="upcomingevent", old_name="end", new_name="end_date",
        ),
        migrations.RenameField(
            model_name="upcomingevent", old_name="start", new_name="start_date",
        ),
    ]
