# Generated by Django 4.2.13 on 2026-02-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_alter_upcomingevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puppy",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=5, null=True
            ),
        ),
    ]
