# Generated by Django 4.2.13 on 2026-02-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_alter_puppy_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="puppy",
            name="litter",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
