# Generated by Django 4.2.13 on 2026-02-25 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0021_alter_puppy_litter"),
    ]

    operations = [
        migrations.DeleteModel(name="Litter",),
    ]
