# Generated by Django 4.2.13 on 2026-02-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_delete_litter"),
    ]

    operations = [
        migrations.RenameField(model_name="dog", old_name="photo", new_name="photo_1",),
        migrations.AddField(
            model_name="dog",
            name="photo_2",
            field=models.ImageField(blank=True, null=True, upload_to="dogs/photos/"),
        ),
        migrations.AddField(
            model_name="dog",
            name="photo_3",
            field=models.ImageField(blank=True, null=True, upload_to="dogs/photos/"),
        ),
        migrations.AddField(
            model_name="dog",
            name="photo_4",
            field=models.ImageField(blank=True, null=True, upload_to="dogs/photos/"),
        ),
    ]
