# Generated by Django 4.2.13 on 2026-02-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_rename_photo_dog_photo_1_dog_photo_2_dog_photo_3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="puppy", name="description", field=models.TextField(blank=True),
        ),
    ]
